attributes:
- beginString: ((\/\/)|\s|^)(http://|https://)
  endString: (\n|\s|\\)
  ignoreCase: true
  regularExpression: true
- beginString: '[@|$][\w]+'
  regularExpression: true
characters:
- beginString: ''''
  endString: ''''
- beginString: '[<|>|?|+|\-|*|=|\\|;|"|''|~|`|!|%|^|&|*|(|)|\[|\]|\:|\.]'
  ignoreCase: false
  regularExpression: true
commands: []
commentDelimiters:
  beginDelimiter: /*
  endDelimiter: '*/'
  inlineDelimiter: '# '
comments:
- beginString: (\s#)|(^#)
  endString: $
  ignoreCase: false
  regularExpression: true
completions: []
extensions:
- keyString: txt
interpreters: []
keywords:
- beginString: class
- beginString: const
- beginString: enum
- beginString: for
- beginString: func
- beginString: if
- beginString: import
- beginString: return
- beginString: static
- beginString: switch
kind: general
metadata:
  author: fistnine
  lastModified: '2022-06-19'
  version: '1.0'
numbers:
- beginString: '[0-9]'
  ignoreCase: false
  regularExpression: true
outlineMenu:
- beginString: ^(#.+)$
  bold: true
  ignoreCase: true
- beginString: ^([\t ]+#.+)$
  ignoreCase: true
  italic: true
  underline: false
strings:
- beginString: '"'
  endString: '"'
  ignoreCase: true
  regularExpression: false
- beginString: 《
  endString: 》
  ignoreCase: true
  regularExpression: false
types:
- beginString: bool
  ignoreCase: true
- beginString: error
  ignoreCase: true
  regularExpression: false
- beginString: float
  ignoreCase: true
- beginString: int
  ignoreCase: true
- beginString: string
  ignoreCase: true
  regularExpression: false
- beginString: void
  ignoreCase: true
  regularExpression: false
values:
- beginString: 'false'
  ignoreCase: true
  regularExpression: false
- beginString: 'true'
  ignoreCase: true
  regularExpression: false
variables: []
